### ISSUE TITLE
Neon.yaml being over-written

### ISSUE THREAD

**Issue by Olzeke51** [OpenVoiceOS/ovos-gui-plugin-shell-companion#29]
when 'wallpaper rotation is turned on {via gui/settings/display/}; the user 'neon.yaml' file is changed to accommodate
the PHAL object for rotation: eliminating any personal settings {blacklisted skills , log_level=DEBUG, etc.]
this happens every 30 seconds
```
PHAL:
  ovos-PHAL-plugin-wallpaper-manager:
    module: ovos-PHAL-plugin-wallpaper-manager
    wait_for_gui: false
    lang: en-us
    selected_provider: skill-ovos-homescreen.openvoiceos
    selected_wallpaper: /home/neon/venv/lib/python3.10/site-packages/skill_ovos_homescreen/ui/wallpapers/background-01.png
    wallpaper_rotation_time: 30
    wallpaper_rotation: true
```
